server:
  port: 8080
spring:
  application:
    name: labo-06
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:3030/realms/capas
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/capas
    username: postgres
    password: 12345

keycloak:
  server-url: http://localhost:3030
  realm: capas
  client-id: backend-client
  client-secret: DoBnieEkGcWAeMBOU2S6AZDDDuTvNQPC